steps:
- name: 'node:latest'
  id: Perform Unit Tests
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd ${_APP_DIR} && npm install && npm test'

- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '-t'
  - '${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
  - '${_APP_DIR}/'